### PR TITLE
Reset the packet payload before replying to a request

### PR DESCRIPTION
**Pull request by aabadie**
I entered a bug while playing with PUT requests with nanocoap : if I send a PUT request with `10` as payload and then send another PUT request with `2`, the request handler (e.g the function pointer linked to the PUT endpoint) receives `20`.
This is because the payload buffer was not reset between with the 2 requests. Normally, this PR solves this.

I'll provide another PR for the nanocoap_server example in RIOT : it adds a resource that can be accessed via GET and updated via PUT. Initially, I just wanted to illustrate how to use the GET and PUT CoAP requests with nanocoap on RIOT but felt into this issue.

### CODE REVIEW

**Comment by kaspar030** [comment]
Looking good! Can't test right now, though.

**Comment by aabadie** [comment]
Actually, I don't have the issue anymore. The [related PR in RIOT] (https://github.com/RIOT-OS/RIOT/issues/6136) works well without this change.
Closing this one but feel to reopen if you think it still makes sense.

**Comment by aabadie** [comment]
Reopening because the problem is always there. I think I still had this version built locally and I got confused with my last try.

This PR indeed fixes the issue.

**Comment by aabadie** [comment]
ping

**Comment by kaspar030** [comment]
@aabadie I don't see why this is necessary. The second PUT should get a packet with the smaller length. Why does clearing the buffer change the length perceived for the second PUT?

It's just a malloc, but I'd like to understand...

**Comment by aabadie** [comment]
>  The second PUT should get a packet with the smaller length. Why does clearing the buffer change the length perceived for the second PUT?

Just changed the example in the RIOT side by taking into account the payload_len field and all is working. I'll update the PR there so we can close this one here (again).

**Comment by kaspar030** [comment]
ok, thanks for looking deeper!

**Pull request closed without merging**
